// Generated by CoffeeScript 1.3.3
(function() {
  var async, config, request;

  async = require("async");

  request = require("request");

  config = require("../config").config;

  exports.getCountries = function(countries, onDone) {
    var freebaseCountries;
    freebaseCountries = [];
    return async.forEach(countries, function(country, ck) {
      var requestDelay;
      console.log(country);
      requestDelay = 1000 / config.freebase.requestsPerSecond;
      return request({
        url: 'https://www.googleapis.com/freebase/v1/mqlread?query={"type":"/location/country","name":"' + country + '","/common/topic/alias":[]}&key=AIzaSyBZF_jfqQ0HjXaEWsNCXkpzTSVpxvPKulY'
      }, function(err, resp, body) {
        var json;
        if (body) {
          body = body.replace(/\n/, "");
        }
        json = JSON.parse(body);
        if (!json.error && json.result) {
          freebaseCountries.push({
            name: json.result.name,
            alias: json.result["/common/topic/alias"]
          });
        }
        return ck(json.error);
      });
    }, function(err, ck) {
      return onDone(err, freebaseCountries);
    });
  };

}).call(this);
