// Generated by CoffeeScript 1.3.3
(function() {
  var csvSourceParser;

  csvSourceParser = require("./csvSourceParser");

  exports.get = function(type) {
    switch (type) {
      case "csv":
        return csvSourceParser;
    }
  };

}).call(this);
