// Generated by CoffeeScript 1.3.3
(function() {

  exports.config = {
    freebase: {
      key: "AIzaSyBZF_jfqQ0HjXaEWsNCXkpzTSVpxvPKulY"
    },
    mongo: {
      uri: "mongodb://baio:prodigy123@ds037837.mongolab.com:37837/dchamber"
    }
  };

}).call(this);
