// Generated by CoffeeScript 1.3.3
(function() {
  var country;

  country = require("./Chamber/country-iso-mongo");

  country.populate(function(err) {
    return console.log(err);
  });

}).call(this);
