// Generated by CoffeeScript 1.3.3
(function() {
  var mongoStorage;

  mongoStorage = require("./mongoStorage");

  exports.get = function(type) {
    switch (type) {
      case "mongo":
        return mongoStorage.Storage;
    }
  };

}).call(this);
