// Generated by CoffeeScript 1.3.3
(function() {
  var request;

  request = require("request");

  exports.request = function(req, onDone) {
    return request(req, function(err, resp, body) {
      return onDone(err, body);
    });
  };

}).call(this);
