// Generated by CoffeeScript 1.3.3
(function() {

  exports.postProcess = function(item) {
    var parts;
    parts = item.name.split(",");
    if (parts.length === 2) {
      item.name = parts[0].trim();
      item.alias = [parts[1].trim() + " " + parts[0].trim()];
    }
    switch (item.name.toLowerCase()) {
      case "united states":
        item.name = "united states of america";
    }
    return item;
  };

}).call(this);
